project_id = "ubksvdbnuusccjxicsnk"

[functions.create-user-from-participante]
verify_jwt = false

[functions.delete-orphan-user]
verify_jwt = false

[functions.delete-user-complete]
verify_jwt = false

[functions.notify-admin-new-user]
verify_jwt = false

[functions.notify-user-approved]
verify_jwt = false

[functions.register-with-congregation]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false
